---
- name: make sure installed wget
  yum: name=wget 
- name: getting pkg from web ...
  shell: wget {{ url_pkg_7 }} 
  when: ansible_distribution == "7"
- name: getting pkg from web ...
  shell: wget {{ url_pkg_8 }} 
  when: ansible_distribution == "8"
...
