---
# link_dir: /usr/local/mariadb-10.2.27-linux-x86_64
- name: mkdir /usr/local/mysql 
  file: src={{ link_dir_7 }} dest=/usr/local/mysql state=link
  when: ansible_distribution == "7"

# link_dir: /usr/local/mariadb-10.2.29-linux-systemd-x86_64.tar.gz
- name: mkdir /usr/local/mysql 
  file: src={{ link_dir_8 }} dest=/usr/local/mysql state=link
  when: ansible_distribution == "8"
