---
## remove remote mysql
- name: remove mysql on centos7
  shell: rm -rf /data/mysql /usr/local/mysql /etc/my.cnf.d/ /etc/my.cnf /etc/profile.d/mysql.sh /etc/init.d/mysqld
  when: ansible_distribution == "7"
- name: remove mysql on centos8
  shell: rm -rf /data/mysql /usr/local/mysql /etc/my.cnf.d/ /etc/my.cnf /etc/profile.d/mysql.sh /usr/lib/systemd/system/mariadb.service
  when: ansible_distribution == "8"
...
