- name: make service script ready
  shell: /bin/cp /usr/local/mysql/support-files/mysql.server /etc/init.d/mysqld; /etc/init.d/mysqld start; chkconfig --add mysqld; chkconfig mysqld on
  when: ansible_distribution == "7"
- name: make service script ready
  shell: /bin/cp /usr/local/mysql/support-files/systemd/mariadb.service
  when: ansible_distribution == "8"
