---
apr_pkg: ansible_exercise/roles/httpd_compile/files/apr-1.7.0.tar.bz2
apr: apr-1.7.0
apr_util_pkg: ansible_exercise/roles/httpd_compile/files/apr-util-1.6.1.tar.bz2
apr_util: apr-util-1.6.1
httpd_pkg: ansible_exercise/roles/httpd_compile/files/httpd-2.4.41.tar.gz
httpd: httpd-2.4.41
deps: ["gcc","pcre-devel","openssl-devel","expat-devel"]
compile_opt: "--enable-so --enable-ssl --enable-cgi --enable-rewrite --with-zlib --with-pcre --enable-modules=most --enable-mpms-shared=all --with-mpm=prefork --with-included-apr"
...
